//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO
    {
        public int certificado_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string certificado_url { get; set; }
        public System.DateTime fecha_otorgamiento { get; set; }
        public int CERTIFICACION_certificacion_id { get; set; }
        public int INSIGNIA_insignia_id { get; set; }
    
        public virtual CERTIFICACION CERTIFICACION { get; set; }
        public virtual INSIGNIA INSIGNIA { get; set; }
    }
}
