//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPETENCIA()
        {
            this.EVENTO = new HashSet<EVENTO>();
            this.INSIGNIA = new HashSet<INSIGNIA>();
        }
    
        public int competencia_id { get; set; }
        public string competencia_conocimiento { get; set; }
        public int AREA_area_id { get; set; }
        public int NIVEL_nivel_id { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual NIVEL NIVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSIGNIA> INSIGNIA { get; set; }
    }
}
