//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.ASISTENCIA = new HashSet<ASISTENCIA>();
            this.INSIGNIA1 = new HashSet<INSIGNIA>();
        }
    
        public int evento_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo_evento { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public System.TimeSpan hora_evento { get; set; }
        public string lugar_evento { get; set; }
        public int AREA_area_id { get; set; }
        public int COMPETENCIA_competencia_id { get; set; }
        public string USUARIO_rut { get; set; }
        public Nullable<int> INSIGNIA_insignia_id { get; set; }
    
        public virtual AREA AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENCIA> ASISTENCIA { get; set; }
        public virtual COMPETENCIA COMPETENCIA { get; set; }
        public virtual INSIGNIA INSIGNIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSIGNIA> INSIGNIA1 { get; set; }
    }
}
