//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.ASISTENCIA = new HashSet<ASISTENCIA>();
            this.INSCRIPCION = new HashSet<INSCRIPCION>();
            this.INSIGNIA = new HashSet<INSIGNIA>();
            this.OTORGAR_INSIGNIA_P2 = new HashSet<OTORGAR_INSIGNIA_P2>();
            this.OTORGAR_INSIGNIA_P3 = new HashSet<OTORGAR_INSIGNIA_P3>();
        }
    
        public int evento_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo_evento { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_evento { get; set; }
        public System.TimeSpan hora_evento { get; set; }
        public string lugar_evento { get; set; }
        public string imagen_url_evento { get; set; }
        public int AREA_area_id { get; set; }
        public int COMPETENCIA_competencia_id { get; set; }
    
        public virtual AREA AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENCIA> ASISTENCIA { get; set; }
        public virtual COMPETENCIA COMPETENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCION> INSCRIPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSIGNIA> INSIGNIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTORGAR_INSIGNIA_P2> OTORGAR_INSIGNIA_P2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTORGAR_INSIGNIA_P3> OTORGAR_INSIGNIA_P3 { get; set; }
    }
}
