//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFO_PERFIL
    {
        public int info_perfil_id { get; set; }
        public string escuela { get; set; }
        public string carrera { get; set; }
        public string sede { get; set; }
        public string USUARIO_rut { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
