//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTORGAR_INSIGNIA_P2
    {
        public bool registro_insignia_evento { get; set; }
        public string contribucion_evento { get; set; }
        public System.DateTime fecha_registro_otorgamiento { get; set; }
        public string USUARIO_rut { get; set; }
        public int EVENTO_evento_id { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
