//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO_CERTIFICADO
    {
        public System.DateTime fecha_otorgamiento { get; set; }
        [MaxLength]
        public string certificado_url { get; set; }
        public int CERTIFICADO_certificado_id { get; set; }
        public string USUARIO_rut { get; set; }
    
        public virtual CERTIFICADO CERTIFICADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
