//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmPoderTIC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ASISTENCIA = new HashSet<ASISTENCIA>();
            this.CONTROL_INSIGNIA = new HashSet<CONTROL_INSIGNIA>();
            this.INFO_PERFIL = new HashSet<INFO_PERFIL>();
            this.INSCRIPCION = new HashSet<INSCRIPCION>();
            this.NOTIFICACION = new HashSet<NOTIFICACION>();
            this.OTORGAR_INSIGNIA_P2 = new HashSet<OTORGAR_INSIGNIA_P2>();
            this.OTORGAR_INSIGNIA_P3 = new HashSet<OTORGAR_INSIGNIA_P3>();
            this.USUARIO_CERTIFICADO = new HashSet<USUARIO_CERTIFICADO>();
        }

        [Required(ErrorMessage = "El RUT es obligatorio")]
        [RegularExpression(@"^[0-9]{7,8}-[0-9Kk]$", ErrorMessage = "Formato de RUT inválido")]
        public string rut { get; set; }

        [Required(ErrorMessage = "El Nombre es obligatorio")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El Apellido es obligatorio")]
        public string apellido_paterno { get; set; }

        public string apellido_materno { get; set; }

        [Required(ErrorMessage = "El Correo es obligatorio")]
        public string correo_electronico { get; set; }

        [Required(ErrorMessage = "La Contraseña es obligatorio")]
        public string contraseña { get; set; }
        public string token { get; set; }
        public string token_reset_contraseña { get; set; }
        public Nullable<System.DateTime> fecha_solicitud_reset_contraseña { get; set; }
        public bool estado_confirmacion { get; set; }
        public bool activo { get; set; }
        public int TIPO_PERFIL_tipo_perfil_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENCIA> ASISTENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_INSIGNIA> CONTROL_INSIGNIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFO_PERFIL> INFO_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCION> INSCRIPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTORGAR_INSIGNIA_P2> OTORGAR_INSIGNIA_P2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTORGAR_INSIGNIA_P3> OTORGAR_INSIGNIA_P3 { get; set; }
        public virtual TIPO_PERFIL TIPO_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_CERTIFICADO> USUARIO_CERTIFICADO { get; set; }
    }
}
